#!/bin/bash
disk_usage=$( df -HT| grep -vE 'tmp|File')
disk_threshold=1
message=""

while IFS= read line
do 
   usage=$(echo $line | awk '{print $6F}' | cut -d % -f1)
   partion=$(echo $line | awk '{print $1F}')
  if [ $usage -ge $disk_threshold ]
  then 
       $message+="disk usage is heavy at $partion - $usage"
   fi   
done <<< $disk_usage

echo "$message"